# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket = "meshcloud-tf-states"
    prefix = "trial-cloudfoundation/foundations/meshstack-trial/platforms/aks/idp/infra/cluster-issuer"
  }
}
